name: RSS to Slack (hourly)

on:
  schedule:
    - cron: "0 * * * *"  # 毎時0分（UTC）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          FEED_URLS: ${{ secrets.FEED_URLS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          POST_WINDOW_MIN: ${{ secrets.POST_WINDOW_MIN }}
        run: python rss_to_slack.py
