name: AI記事要約配信

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: ファイル確認
        run: |
          echo "=== 基本確認 ==="
          pwd
          ls -la
          echo "=== Pythonファイル検索 ==="
          find . -name "*.py" -type f

      - name: Python実行テスト
        run: |
          echo "=== Python実行テスト ==="
          python ai_rss_summarizer.py

      - name: Slack通知
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"🔍 新しいテストワークフロー実行完了！"}' \
            $SLACK_WEBHOOK_URL
