name: AI記事要約配信

on:
  schedule:
    - cron: "30 */3 * * *"  # 3時間おきの30分（UTC: 0:30, 3:30, 6:30, 9:30...）
  workflow_dispatch:

concurrency:
  group: ai-news
  cancel-in-progress: true

jobs:
  ai-summarize:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python環境をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 依存関係をインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Slack接続テスト（AI記事要約）
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python - <<'PY'
          import os, requests
          print("🤖 AI記事要約bot稼働中...")
          r = requests.post(os.environ["SLACK_WEBHOOK_URL"], json={"text":"🤖 AI記事要約bot稼働中"})
          print("status:", r.status_code, r.text[:200])
          PY

      - name: AI記事要約システムを実行
        env:
          AI_FEED_URLS: ${{ secrets.AI_FEED_URLS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          HUGGINGFACE_API_KEY: ${{ secrets.HF_TOKEN }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          POST_WINDOW_MIN: ${{ secrets.POST_WINDOW_MIN_AI }}
          MAX_POSTS: ${{ secrets.MAX_POSTS_AI }}
          DRY_RUN: ${{ secrets.DRY_RUN }}
        run: |
          echo "Debug: AI_FEED_URLS = $AI_FEED_URLS"
          python ai_rss_summarizer.py