name: RSS to Slack (hourly)

on:
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Build
        run: gradle build -x test
      - name: Run
        env:
          FEED_URLS: ${{ secrets.FEED_URLS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          POST_WINDOW_MIN: ${{ vars.POST_WINDOW_MIN }}
        run: gradle run
